repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: strip-claude-attribution
        name: Strip AI Attribution
        entry: python scripts/strip-claude-attribution.py --fix
        language: system
        files: '\.(py|md|yml|yaml|json|js|ts|tsx)$'
        require_serial: true
        pass_filenames: false

      - id: sync-github-status
        name: Sync GitHub Project Status to Files
        entry: python scripts/sync-status-to-files.py nestorwheelock/osint-framework --project-number 5
        language: system
        files: '^planning/.*\.md$'
        require_serial: true
        verbose: true
        pass_filenames: false
