# Generated by Django 4.2.7 on 2025-09-29 00:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the session",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        help_text="Current status of the investigation session",
                        max_length=20,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        default=dict,
                        help_text="Session configuration including search engines, limits, and filters",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the session was started (moved to running)",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the session was completed or failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the session was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the session was last modified",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject being investigated in this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Investigation Session",
                "verbose_name_plural": "Investigation Sessions",
                "db_table": "investigation_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
