# Generated by Django 4.2.7 on 2025-09-29 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subjects", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(help_text="The search query text")),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("general", "General Search"),
                            ("person", "Person Search"),
                            ("organization", "Organization Search"),
                            ("domain", "Domain Search"),
                            ("email", "Email Search"),
                        ],
                        default="general",
                        help_text="Type of search query",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the search was created",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject this search belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Query",
                "verbose_name_plural": "Search Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the search result", max_length=500
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL of the search result", max_length=2000
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonicalized version of the URL",
                        max_length=2000,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description or snippet from the search result",
                    ),
                ),
                (
                    "search_engine",
                    models.CharField(
                        help_text="Search engine that provided this result",
                        max_length=50,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(help_text="Position in search results"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this result was captured",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        help_text="The search query that generated this result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="search.searchquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Result",
                "verbose_name_plural": "Search Results",
                "ordering": ["rank"],
                "unique_together": {("query", "url", "search_engine")},
            },
        ),
    ]
